version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mypassword
    ports:
      - "8080:8080"
    restart: always
    volumes: 
      - dbdata:/var/lib/postgresql/data

  go:
    container_name: ethservice
    ports:
     - "80:80"
    build:
      context: .
    depends_on:
      - "postgres"
      
volumes:
  dbdata: